# Generated by Django 5.2.4 on 2025-07-04 10:48

import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to=player.models.cover_image_path)),
            ],
        ),
    ]
