# Generated by Django 5.2.4 on 2025-07-04 10:51

import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=None, upload_to=player.models.file_path),
            preserve_default=False,
        ),
    ]
