# Generated by Django 5.2.4 on 2025-07-04 14:05

import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=player.models.cover_image_path),
        ),
    ]
